### PR TITLE
Add RoboUniView paper

### PR DESCRIPTION
**Pull request by fengxiuyaun**
add RoboUniView which is MLLM

### CODE REVIEW

**Comment by mees** [comment]
Thanks! Could you provide the pretrained checkpoint in your repo so people can verify the reported numbers?

**Comment by mees** [comment]
Besides, there are a few high performing related works that you are missing in your paper, would be nice to cite them in your paper too.
Screenshot from 2024-06-29 15-33-00

**Comment by fengxiuyaun** [comment]
Done. We released weights and added all methods on the github.

**Comment by mees** [comment]
Could you point me to the checkpoint? I don't find it in your repo. Also, the authors of the the aforementioned works, would probably grateful if you cite them in your paper.

**Comment by fengxiuyaun** [comment]
Thanks. We have updated Table 1 in our paper (https://arxiv.org/abs/2406.18977v2) and uploaded the checkpoint to GitHub (https://github.com/liufanfanlff/RoboUniview).

**Comment by fengxiuyaun** [comment]
@mees  Hi, Mees. We have updated. Hope you have some time to update our method on the leaderboard.

**Comment by mees** [comment]
Sorry for the delay @fengxiuyaun I have added your paper to the leaderboard and the the calvin readme. BTW, you have a typo in your paper title "Manipulaiton" vs "Manipulation" on arxiv, you might want to fix that.

**Comment by fengxiuyaun** [comment]
Oh, thank you.

**Pull request closed without merging**
